language: node_js
node_js: 12

script:
  - npm run lint
  - npm run build
  - npm run build:css
  - npm run build:full
  - npm run build:component

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: beta
  script:
    - npm run semantic-release
