declare module 'vue' {
  export interface GlobalComponents {
    /* Basic */
    FxButton: typeof import('vfox/es')['Button']
    FxButtonGroup: typeof import('vfox/es')['ButtonGroup']
    FxIcon: typeof import('vfox/es')['Icon']
    FxImage: typeof import('vfox/es')['Image']
    FxPopover: typeof import('vfox/es')['Popover']
    FxDrawer: typeof import('vfox/es')['Drawer']
    FxModal: typeof import('vfox/es')['Modal']
    FxDropdown: typeof import('vfox/es')['Dropdown']
    FxScrollView: typeof import('vfox/es')['ScrollView']

    /* Form  */
    FxSwitch: typeof import('vfox/es')['Switch']
    FxSlider: typeof import('vfox/es')['Slider']
    FxRadioGroup: typeof import('vfox/es')['RadioGroup']
    FxRadio: typeof import('vfox/es')['Radio']
    FxCheckboxGroup: typeof import('vfox/es')['CheckboxGroup']
    FxCheckbox: typeof import('vfox/es')['Checkbox']
    FxInput: typeof import('vfox/es')['Input']
    FxForm: typeof import('vfox/es')['Form']
    FxFormItem: typeof import('vfox/es')['FormItem']
    FxFormFooter: typeof import('vfox/es')['FormFooter']
    FxCascader: typeof import('vfox/es')['Cascader']
    FxCascaderPopup: typeof import('vfox/es')['CascaderPopup']
    FxRate: typeof import('vfox/es')['Rate']
    FxStepper: typeof import('vfox/es')['Stepper']
    FxPickerView: typeof import('vfox/es')['PickerView']
    FxPicker: typeof import('vfox/es')['Picker']
    FxPickerPopup: typeof import('vfox/es')['PickerPopup']
    FxCalendarView: typeof import('vfox/es')['CalendarView']
    FxCalendarPopup: typeof import('vfox/es')['CalendarPopup']
    FxCalendar: typeof import('vfox/es')['Calendar']
    FxSearchBar: typeof import('vfox/es')['SearchBar']
    FxNumberKeyboard: typeof import('vfox/es')['NumberKeyboard']
    FxImageUploader: typeof import('vfox/es')['ImageUploader']
    FxDatePicker: typeof import('vfox/es')['DatePicker']
    FxDatePickerPopup: typeof import('vfox/es')['DatePickerPopup']
    FxDatePickerView: typeof import('vfox/es')['DatePickerView']
    FxRange: typeof import('vfox/es')['Range']

    /* Feedback */
    FxToast: typeof import('vfox/es')['Toast']
    FxNotify: typeof import('vfox/es')['Notify']
    FxDialog: typeof import('vfox/es')['Dialog']
    FxActionSheet: typeof import('vfox/es')['ActionSheet']
    FxPopDialog: typeof import('vfox/es')['PopDialog']
    FxSwipeCell: typeof import('vfox/es')['SwipeCell']

    /* Navigation */
    FxTab: typeof import('vfox/es')['Tab']
    FxSideTab: typeof import('vfox/es')['SideTab']
    FxTabBar: typeof import('vfox/es')['TabBar']
    FxBackTop: typeof import('vfox/es')['BackTop']
    FxNavBar: typeof import('vfox/es')['NavBar']
    FxPopMenu: typeof import('vfox/es')['PopMenu']
    FxTabView: typeof import('vfox/es')['TabView']
    FxTabViewItem: typeof import('vfox/es')['TabViewItem']
    FxSticky: typeof import('vfox/es')['Sticky']
    FxStickyView: typeof import('vfox/es')['StickyView']
    FxStickyViewItem: typeof import('vfox/es')['StickyViewItem']
    FxScrollTab: typeof import('vfox/es')['ScrollTab']
    FxScrollTabItem: typeof import('vfox/es')['ScrollTabItem']
    FxIndexView: typeof import('vfox/es')['IndexView']
    FxIndexViewItem: typeof import('vfox/es')['IndexViewItem']
    FxFixed: typeof import('vfox/es')['Fixed']
    FxPagination: typeof import('vfox/es')['Pagination']

    /* Show */
    FxSwiper: typeof import('vfox/es')['Swiper']
    FxSwiperItem: typeof import('vfox/es')['SwiperItem']
    FxFlatList: typeof import('vfox/es')['FlatList']
    FxEmpty: typeof import('vfox/es')['Empty']
    FxSkeleton: typeof import('vfox/es')['Skeleton']
    FxSkeletonAvatar: typeof import('vfox/es')['SkeletonAvatar']
    FxSkeletonTitle: typeof import('vfox/es')['SkeletonTitle']
    FxSkeletonParagraph: typeof import('vfox/es')['SkeletonParagraph']
    FxSkeletonButton: typeof import('vfox/es')['SkeletonButton']
    FxSkeletonImage: typeof import('vfox/es')['SkeletonImage']
    FxImagePreview: typeof import('vfox/es')['ImagePreview']
    FxCell: typeof import('vfox/es')['Cell']
    FxGroup: typeof import('vfox/es')['Group']
    FxRow: typeof import('vfox/es')['Row']
    FxCol: typeof import('vfox/es')['Col']
    FxNoticeBar: typeof import('vfox/es')['NoticeBar']
    FxDivider: typeof import('vfox/es')['Divider']
    FxCollapse: typeof import('vfox/es')['Collapse']
    FxCollapseItem: typeof import('vfox/es')['CollapseItem']
    FxBadge: typeof import('vfox/es')['Badge']
    FxProgress: typeof import('vfox/es')['Progress']
    FxTag: typeof import('vfox/es')['Tag']
    FxOrder: typeof import('vfox/es')['Order']
    FxCountDown: typeof import('vfox/es')['CountDown']
    FxSteps: typeof import('vfox/es')['Steps']
    FxStep: typeof import('vfox/es')['Step']
    FxPrice: typeof import('vfox/es')['Price']
    FxAvatar: typeof import('vfox/es')['Avatar']
    FxAvatarGroup: typeof import('vfox/es')['AvatarGroup']
    FxTimeline: typeof import('vfox/es')['Timeline']
    FxTimelineItem: typeof import('vfox/es')['TimelineItem']
    FxStopwatch: typeof import('vfox/es')['Stopwatch']
    FxResult: typeof import('vfox/es')['Result']
    FxLoadMore: typeof import('vfox/es')['LoadMore']
    FxTimeAgo: typeof import('vfox/es')['TimeAgo']
    FxCountUp: typeof import('vfox/es')['CountUp']
    FxCircleProgress: typeof import('vfox/es')['CircleProgress']
    FxActivityIndicator: typeof import('vfox/es')['ActivityIndicator']

    /* Other */
    FxCopy: typeof import('vfox/es')['Copy']
  }
}

export {}
